Adding blog post about building Warpinator
AlmaLinux/almalinux.org pull request #219
Opened 2023-06-23 12:05 UTC by sboldyreva

@jaboutboul @bennyvasquez please, review

2023-06-23 14:55 UTC, codyro commented
We may want to consider letting the current (impact of RHEL changes) blog post stay at the top for a few days before merging this in. Just my 0.02.

2023-07-18 20:50 UTC, bennyvasquez requested changes
Overall, I love this post! Two questions for you, @sboldyreva:

1) do any of these directions need to be adjusted/changed in light of the new build processes we're using? I assume not, but I want to make sure.

2) Should we include something about adding tests for these packages, given that the OpenQA post will be published just before this one?

2023-07-18 20:50 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +date: '2023-06-23'
```suggestion
date: '2023-06-27'
```

2023-07-18 20:50 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +As [I've begun](https://almalinux.org/blog/building-pantheon-for-almalinux-9/) to gain some experience in building rpm packages, I've decided to continue and try to build this useful app for AlmaLinu
```suggestion

Hi again! As [I've begun](https://almalinux.org/blog/building-pantheon-for-almalinux-9/) to gain some experience in building rpm packages, I've decided to continue and try to build this useful app for AlmaLinux OS 8 and AlmaLinux OS 9.

## About 
[Warpinator](https://github.com/linuxmint/warpinator), a file-sharing tool by Linux Mint, exemplifies their commitment to a seamless user experience. We owe its success to the dedicated [contributors](https://github.com/linuxmint/warpinator/graphs/contributors) - thank you!

Originally designed for Debian-based Linux, Warpinator has grown to serve Windows, Android, iOS, and now RPM-based Linux distros, expanding its capabilities to an increasingly diverse user base.
```

2023-07-18 20:50 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +As [I've begun](https://almalinux.org/blog/building-pantheon-for-almalinux-9/) to gain some experience in building rpm packages, I've decided to continue and try to build this useful app for AlmaLinu
I moved your last line to the top, above the 'about' to give readers a little context about what they would learn in this post.

2023-07-24 17:45 UTC, sboldyreva commented
@bennyvasquez 

1. current versions are not affected by the changes in the building process 
2. for now, as I am aware, we don't test packages via openQA, but some tests were run while building process in AlmaLinux Build System as it has Test System

2023-07-27 21:34 UTC, bennyvasquez commented
Ah, sorry, I missed getting this out today, due to the security stuff. I don't want to publish it tomorrow, as things published on Friday tend to get missed by most of the world. We'll get it out next week!

2023-08-07 15:47 UTC, bennyvasquez approved these changes
with the date update, we can get this out today!

2023-08-07 15:47 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +date: '2023-06-27'
```suggestion
date: '2023-08-07'
```

2023-08-07 17:10 UTC, codyro commented
I'll update the CONTRIBUTING doc once I'm back from lunch :). 

You can copy that syntax; however, it supports triple backticks, which is what most people are familiar with, so I'll document that and adjust the referenced post accordingly.

2023-08-07 18:04 UTC, codyro commented
@bennyvasquez @sboldyreva https://github.com/AlmaLinux/almalinux.org/pull/292

2023-08-07 18:20 UTC, bennyvasquez approved these changes
Adding formatting lines

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +```
```suggestion
```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +```
```suggestion
```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +```
```suggestion
```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +  ```
```suggestion
  ```bash
```

2023-08-07 18:20 UTC, bennyvasquez commented on content/blog/building-warpinator-for-almalinux.md
> +```
```suggestion
```bash
```

2023-08-07 18:39 UTC, merged