Added a blog post call for testers for security updates
AlmaLinux/almalinux.org pull request #295
Opened 2023-08-10 19:12 UTC by sboldyreva

2023-08-10 19:13 UTC, sboldyreva commented
@bennyvasquez @jaboutboul

2023-08-10 19:31 UTC, codyro commented
Looks good to me as-is. 

+1

2023-08-10 19:31 UTC, codyro approved these changes

2023-08-10 20:26 UTC, bennyvasquez requested changes
Suggestions for english and clarity.

2023-08-10 20:26 UTC, bennyvasquez commented on content/blog/testers-needed-for-updated-packages-intel-and-amd-cpus-affected.md
> +As AlmaLinux OS has changed its build processes in order to be [ABI compatible](https://almalinux.org/blog/future-of-almalinux/) with Red Hat, **Testing** repo has been created for packages that diff
```suggestion
 As we recently changed the build process for AlmaLinux OS, and are now aiming to be [ABI compatible](https://almalinux.org/blog/future-of-almalinux/) with Red Hat Enterprise Linux, we are now able to release updates without waiting for the patches to be released upstream. To help accommodate that, a **Testing** repo has been created for packages that differ from RHEL and require additional testing by our users. 
```

2023-08-10 20:26 UTC, bennyvasquez commented on content/blog/testers-needed-for-updated-packages-intel-and-amd-cpus-affected.md
> +It's highly recommended to enable **Testing** repo on all non-production machines to participate in AlmaLinux development.
```suggestion
We highly recommend and encourage you to enable the **Testing** repo on all non-production machines to expand participation in the AlmaLinux development.
```

2023-08-10 20:26 UTC, bennyvasquez commented on content/blog/testers-needed-for-updated-packages-intel-and-amd-cpus-affected.md
> +The vulnerability can be mitigated by updating CPU microcode - `microcode_ctl` package:
```suggestion
Once you enable the **Testing** repo, the vulnerability can be mitigated by updating CPU microcode - `microcode_ctl` package:
```

2023-08-10 20:26 UTC, bennyvasquez commented on content/blog/testers-needed-for-updated-packages-intel-and-amd-cpus-affected.md
> +[CVE-2023-20569](https://nvd.nist.gov/vuln/detail/CVE-2023-20569) vulnerability affects "Zen 3" and "Zen 4" AMD CPUs as it may allow an attacker to influence the return address prediction. This may p
```suggestion
The recently announced [CVE-2023-20569](https://nvd.nist.gov/vuln/detail/CVE-2023-20569) vulnerability affects "Zen 3" and "Zen 4" AMD CPUs as it may allow an attacker to influence the return address prediction. This may potentially lead to information disclosure.
```

2023-08-10 20:26 UTC, bennyvasquez commented on content/blog/testers-needed-for-updated-packages-intel-and-amd-cpus-affected.md
> +The vulnerability can be partially mitigated by updating `linux-firmware` package:
```suggestion
Once you enable the **Testing** repo, the vulnerability can be partially mitigated by updating `linux-firmware` package:
```

2023-08-10 20:26 UTC, bennyvasquez commented on content/blog/testers-needed-for-updated-packages-intel-and-amd-cpus-affected.md
> +**To update the CPU microcode run the following:**
```suggestion
**To update the CPU microcode run the following or reboot the computer:**
```

2023-08-11 08:00 UTC, andrewlukoshko approved these changes

2023-08-11 17:48 UTC, bennyvasquez approved these changes
Gonna publish this one on Monday

2023-08-11 17:52 UTC, bennyvasquez commented on content/blog/testers-needed-for-updated-packages-intel-and-amd-cpus-affected.md
> +date: '2023-08-10'
```suggestion
date: '2023-08-14'
```

2023-08-11 17:52 UTC, bennyvasquez commented
Schedule for posting on Monday.

2023-08-14 14:04 UTC, merged