New blog contribution guide
AlmaLinux/almalinux.org pull request #315
Opened 2023-08-28 16:47 UTC by bennyvasquez

I thought I'd submitted this already, but apparently not!

2023-08-28 17:46 UTC, codyro commented
Can I add some formatting to your branch? The content would remain the same, but things like filenames I'll tidy up (EX, blah/partial/single.html -> `/blah/partial/single.html`).

Regarding the content, I think we should clarify a few things:

> by submitting content to the AlmaLinux website, you are affirming that you are the sole author of all text and images used in the post, and that you own all rights to publish said content.

Should we require any content/assets under specific licenses?

> external links are allowed, but links to paywalled websites or obvious use of a blogpost on the AlmaLinux site as an SEO builder for another website is prohibited.

We need to be *very* careful here. We should specify that all external links will be `nofollow`ed (https://en.wikipedia.org/wiki/Nofollow) and will need to be reviewed. This should curb any SEO/spam content from the get-go. 

Also, a space between `blog` & `post` :).

My other suggestion would be to link to the https://github.com/AlmaLinux/almalinux.org/tree/master/content/blog page for examples of live blog posts.

2023-08-28 18:11 UTC, bennyvasquez commented
Great feedback, @codyro. Mind another look, when you get a second?

2023-08-31 17:01 UTC, codyro requested changes
Couple of missed style tweaks/broken hyperlink/wrong `hugo serve` command. Looks good otherwise!

2023-08-31 17:01 UTC, codyro commented on CONTRIBUTING.md
> +- by submitting content to the AlmaLinux website, you acknowledge that you are aware of our [https://almalinux.org/p/the-almalinux-os-licensing-policy/license](license policy), are affirming that you
Broken URL/markdown:

> - by submitting content to the AlmaLinux website, you acknowledge that you are aware of our [https://almalinux.org/p/the-almalinux-os-licensing-policy/license](license policy), are affirming that you own all rights to publish said content.

to

> - by submitting content to the AlmaLinux website, you acknowledge that you are aware of our [license policy](https://almalinux.org/p/the-almalinux-os-licensing-policy/license), are affirming that you own all rights to publish said content.

2023-08-31 17:03 UTC, codyro commented on CONTRIBUTING.md
> +- by submitting content to the AlmaLinux website, you acknowledge that you are aware of our [https://almalinux.org/p/the-almalinux-os-licensing-policy/license](license policy), are affirming that you
Oops, looks like that URL is a 404 as well, so that needs be adjusted too.

2023-09-01 19:02 UTC, bennyvasquez commented
@codyro all resolved!

2023-09-02 19:25 UTC, codyro approved these changes

2023-09-02 19:26 UTC, codyro commented
Looks good to merge to me!

2023-09-04 17:09 UTC, merged